# Generated by Django 4.0.1 on 2022-01-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_company_employee_departments_employee_user_and_more'),
        ('records_hours_extras', '0002_recordhourextra_delete_record_hour_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordhourextra',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
            preserve_default=False,
        ),
    ]
