# Generated by Django 4.0.1 on 2022-01-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records_hours_extras', '0003_recordhourextra_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordhourextra',
            options={'ordering': ('id',), 'verbose_name_plural': 'REGISTRO DE HORAS EXTRAS'},
        ),
    ]
