# Generated by Django 4.0.1 on 2022-01-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Nome da Empresa', max_length=100, verbose_name='Nome'),
        ),
    ]
