# Generated by Django 4.0.1 on 2022-01-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('id',), 'verbose_name_plural': 'DEPARTAMENTOS'},
        ),
    ]
