# Generated by Django 4.0.1 on 2022-01-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_company_employee_departments_employee_user_and_more'),
        ('documents', '0002_rename_name_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='belongs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
