# Generated by Django 4.0.1 on 2022-01-15 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_user'),
        ('documents', '0003_document_belongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='belongs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
            preserve_default=False,
        ),
    ]
