# Generated by Django 4.0.1 on 2022-01-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_belongs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('id',), 'verbose_name_plural': 'DOCUMENTOS'},
        ),
    ]
